# Use the official Determinate Systems Nix image
image: determinate/nix:2.28

stages:
  - check
  - build

check:
  stage: check
  script:
    # Look, no extra-experimental-features flag needed anymore!
    - nix flake check --print-build-logs

.docker-build:
  stage: build
  script:
    - nix build .#dockerImage --print-build-logs
    - nix run nixpkgs#skopeo -- copy --dest-creds "$CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD" docker-archive:result docker://$CI_REGISTRY_IMAGE:$IMAGE_TAG

docker-build-main:
  extends: .docker-build
  variables:
    IMAGE_TAG: latest
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

docker-build:
  extends: .docker-build
  variables:
    IMAGE_TAG: $CI_COMMIT_REF_SLUG
  rules:
    - if: '$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'

