image: nixos/nix:2.28.6

# Enable flakes and nix-command globally for all jobs
variables:
  NIX_CONFIG: 'extra-experimental-features = nix-command flakes'

stages:
  - check
  - build

check:
  stage: check
  script:
    # Clean and flag-free!
    - nix flake check --print-build-logs

.docker-build:
  stage: build
  script:
    - nix build .#dockerImage --print-build-logs
    # Default policy.json required by containers libraries (skopeo/podman/buildah)
    - mkdir -p /etc/containers
    - 'echo ''{"default":[{"type":"insecureAcceptAnything"}]}'' > /etc/containers/policy.json'
    - nix run nixpkgs#skopeo -- copy --dest-creds "$CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD" docker-archive:result docker://$CI_REGISTRY_IMAGE:$IMAGE_TAG

docker-build-main:
  extends: .docker-build
  variables:
    IMAGE_TAG: latest
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

docker-build:
  extends: .docker-build
  variables:
    IMAGE_TAG: $CI_COMMIT_REF_SLUG
  rules:
    - if: '$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'
