name: "albumator"
description: "Image uploader/browser using Svelte 5/SvelteKit and Tailwind - https://albumator.sacha.house/"
topics:
  - "svelte"
  - "tailwindcss"
  - "typescript"
homepage: "https://albumator.sacha.house/"
source:
  provider: github
  namespace: "sachahjkl"
  path: "sachahjkl/albumator"
